services:

   # конфигурация для сервисов по умолчанию в *этом* файле
   _defaults:
      autowire: true      # Автоматически внедряет зависимости в ваши сервисы.
      autoconfigure: true # Автоматически регистрирует ваши сервисы как команды, подписчики событий и т.д.

   # Сервис для модификации запросов QueryBuilder в Repository исходя из настроек.
   Maris\Symfony\Company\Service\QueryBuilderModifier: ~

   # Класс репозитория для всех представителей бизнеса.
   Maris\Symfony\Company\Repository\Business\BusinessRepository:
      arguments:
         $registry: '@doctrine'
         $modifier: '@Maris\Symfony\Company\Service\QueryBuilderModifier'



   #Maris\Symfony\Address\:
   #   resource: '../../src/'
   #   exclude: '../../src/{DependencyInjection,Entity,Traits}'